### ISSUE TITLE
Opened "phil pairing" branch, now can't push to gh-pages

### ISSUE THREAD

**Issue by kimhart** [kimhart/Project1_HPmemory#3]
Hey Phil! This morning you created a new branch called Phil Pairing for me and now I'm not sure how to take everything I've worked on since this morning and push it up to gh-pages. I switched back to my gh-branch using checkout branch and re-saved/added/committed/pushed, but nothing is showing up in github.

Help!

**Comment by phlco** [comment]
@kimhart Sorry about that! 

We did the following:

```
$ git checkout -b phil-pairing
```

This created a new branch where you made all your changes.

If you added and commited your changes to that branch, then when you check back to `gh-pages` those changes won't be there, because they're in the other branch.

You'll need to _merge_ those changes from the `phil-pairing` branch _into_ `master` or `gh-pages` You can do that by first checking out `gh-pages` and then running `git merge phil-pairing`

It should look something like this:

```
git checkout gh-pages
git merge phil-pairing
git push origin gh-pages
```

Let me know if that works!
